ALTER PROCEDURE [dbo].[FETCH_EMPLOYEE_MST_RECORD]
(
	@TEM_ID INT
)
AS
BEGIN
	IF(@TEM_ID = 0)
	BEGIN
		SET @TEM_ID = NULL
	END

	SELECT
		 TEM.ID						AS     [ID]
		,TEM_EMPLOYEE_NAME			AS     [EmpName]
		,TEM_EMPLOYEE_GENDER		AS     [Gender]
		,TEM_EMPLOYEE_CITY			AS     [City]
		,TDM.TDM_DEPT_NAME			AS	   [DepartmentName]
		,TEM.TEM_DOB				AS	   [DateOfBirth]
		,ISNULL(TUM.UserName,'')	AS     [CreatedBy]
		,TEM.CREATED_ON				AS     [CreatedOn]
		,ISNULL(TUM1.UserName,'')	AS     [ModifiedBy]
		,TEM.MODIFIED_ON			AS     [ModifiedON]
	FROM 
		TBL_EMPLOYEE_MST TEM
		LEFT JOIN TBL_DEPARTMENT_MST TDM ON (TEM.TEM_DEPARTMENT_ID = TDM.ID)
		LEFT JOIN TBL_USER_MST TUM ON (TEM.CREATED_BY = TUM.ID)
		LEFT JOIN TBL_USER_MST TUM1 ON (TEM.MODIFIED_BY = TUM1.ID)
	WHERE 
		TEM.ID = ISNULL(@TEM_ID, TEM.ID)
		AND ISNULL(TEM.IS_DELETED,0) = 0
END




