ALTER PROCEDURE [dbo].[MANAGE_EMPLOYEE_MST]
(
	 @TEM_ID						INT
	,@TEM_EMPLOYEE_NAME				NVARCHAR(20)
	,@TEM_EMPLOYEE_GENDER			NVARCHAR(20)
	,@TEM_EMPLOYEE_CITY				NVARCHAR(20)
	,@TEM_DOB						DATETIME2		= NULL
	,@TEM_CREATED_BY				INT
	,@TEM_CREATED_ON				DATETIME2
	,@TEM_MODIFIED_BY				INT
	,@TEM_MODIFIED_ON				DATETIME2
	,@RET_VAL						INT OUT
)
AS
BEGIN
	
	IF(@TEM_ID = 0)
		SET @TEM_ID = NULL

	IF(@TEM_CREATED_BY = 0)
		SET @TEM_CREATED_BY = NULL

	IF(@TEM_MODIFIED_BY = 0)
		SET @TEM_MODIFIED_BY = NULL

	IF(@TEM_ID IS NULL)
	BEGIN
		INSERT INTO TBL_EMPLOYEE_MST
		(
			 TEM_EMPLOYEE_NAME		
			,TEM_EMPLOYEE_GENDER	
			,TEM_EMPLOYEE_CITY
			,TEM_DOB		
			,CREATED_BY
			,CREATED_ON
		)
		VALUES
		(
			 @TEM_EMPLOYEE_NAME		
			,@TEM_EMPLOYEE_GENDER	
			,@TEM_EMPLOYEE_CITY	
			,@TEM_DOB	
			,@TEM_CREATED_BY		
			,@TEM_CREATED_ON			 
		)

		SET @RET_VAL = SCOPE_IDENTITY()		
	END
	ELSE
	BEGIN
		UPDATE 
			TBL_EMPLOYEE_MST
		SET 
			TEM_EMPLOYEE_NAME		=	@TEM_EMPLOYEE_NAME	
		   ,TEM_EMPLOYEE_GENDER		= 	@TEM_EMPLOYEE_GENDER
		   ,TEM_EMPLOYEE_CITY		= 	@TEM_EMPLOYEE_CITY	
		   ,TEM_DOB					=	@TEM_DOB
		   ,MODIFIED_ON				=	@TEM_MODIFIED_ON
		   ,MODIFIED_BY				=	@TEM_MODIFIED_BY
		WHERE
			ID						=	@TEM_ID
			
		SET @RET_VAL = @TEM_ID
	END	
	
	--SELECT @RET_VAL
END


